### ISSUE TITLE
Create point lights for sphereMinions

### ISSUE THREAD

**Issue by anjin83** [Chris-Johnston/CSS452Game#33]
Create point lighting for the sphereMinion objects. sphereMinions will emit a small white glowing light source.

**Comment by Chris-Johnston** [comment]
I don't think adding point lights for each object would be a good idea, IIRC the engine had a hardcoded limit (defaults to 4), and this sounds like approaching that limit would be very easy

**Comment by anjin83** [comment]
Yeah, I forgot about the light limit, scrap this idea then
